display availabilities and other changes
motis-project/prima pull request #14
Opened 2024-06-13 10:00 UTC by nilspenzel

move vehicles and tours updates into $effect
filter tours by day
load availabilities and display them in availability view replace button text -> 'Fahrzeug hinzufügen'
update availability (without merging ranges) in ui (not database) when adding (not removing) availability

2024-06-13 12:05 UTC, felixguendling requested changes

2024-06-13 12:05 UTC, felixguendling commented on ui/src/routes/taxi/+page.svelte
> +	let vehicles = $state<Map<number, Vehicle>>(new Map());
die Idee war hier schon die Map zu initialisieren um keine leere Tabelle anzuzeigen, wenn die Seite noch lädt - das funktioniert jetzt wahrscheinlich nicht mehr?

2024-06-13 12:05 UTC, felixguendling commented on ui/src/routes/taxi/+page.server.ts
> +				eb(sql<string>`TO_CHAR(availability.start_time, 'YYYY-MM-DD')`, '=', day_string),
Warum kein Interval-Overlap Check? Könnte es prinzipiell Availabilities geben, die über mehrere Tage / Wochen gehen und somit an dem Tag gelten aber weder `start_time` noch `end_time` ist gleich `day_string`?

2024-06-14 08:22 UTC, felixguendling commented on ui/src/routes/taxi/+page.svelte
> +								{'Fahrzeug hinzuügen'}
```suggestion
								{'Fahrzeug hinzufügen'}
```

2024-06-17 11:12 UTC, felixguendling commented on ui/src/routes/taxi/+page.server.ts
> +			or([
Das ist kein Overlaps Check, richtig? Hier wird nur geprüft, ob Start/End Zeit im Zeitfenster liegt. Das Zeitfenster kann sich aber auch überlappen ohne, dass Start/Ende an dem Tag ist.

2024-06-17 11:12 UTC, felixguendling commented on ui/src/routes/taxi/+page.svelte
> +
```suggestion
```

2024-06-17 11:12 UTC, felixguendling commented on ui/src/routes/taxi/+page.svelte
> +
```suggestion
```

2024-06-17 11:18 UTC, nilspenzel commented on ui/src/routes/taxi/+page.server.ts
> +			or([
Stimmt, werde ich gleich nochmal nachbessern.

2024-06-17 13:25 UTC, felixguendling commented on ui/src/routes/taxi/+page.server.ts
> +	latest_displayed_time.setHours(day.getHours() + 25);
Passt das bzgl. Zeitzone?

2024-06-17 13:40 UTC, nilspenzel commented on ui/src/routes/taxi/+page.server.ts
> +	latest_displayed_time.setHours(day.getHours() + 25);
Ich wollte das Zeitzonen Handling dann im nächsten Pull-Request angehen. Passt das?

2024-06-17 13:55 UTC, felixguendling commented on ui/src/routes/taxi/+page.server.ts
> +	latest_displayed_time.setHours(day.getHours() + 25);
Dann wenigstens hier CET als default Zeitzone wie in der GUI? Sonst sind die Ergebnisse nicht mal konsistent mit dem Frontend Code.

2024-06-18 09:42 UTC, merged