provide time interval handling
motis-project/prima pull request #2
Opened 2024-03-29 11:22 UTC by nilspenzel

2024-03-29 11:40 UTC, felixguendling requested changes

2024-03-29 11:40 UTC, felixguendling commented on src/backend/interval.rs
> +        false
```suggestion
        self.start_time.date() == day || self.end_time.date() == day
```

2024-03-29 11:40 UTC, felixguendling commented on src/backend/interval.rs
> +        };
min/max

2024-03-29 11:40 UTC, felixguendling commented on src/backend/interval.rs
> +        }
min

2024-05-15 14:45 UTC, felixguendling approved these changes

2024-05-21 14:35 UTC, steffenheger approved these changes

2024-05-21 14:39 UTC, merged