add vehicle ui
motis-project/prima pull request #62
Opened 2024-07-15 07:17 UTC by CmdrTMir

2024-07-15 11:16 UTC, felixguendling requested changes
Das Fahrzeug taucht nach dem Hinzufügen nicht in der UI auf. Bitte immer überlegen, was aus Nutzersicht zu erwarten bzw. logisch wäre. Z.B. hier: Fahrzeug hinzufügen = Fahrzeug taucht direkt in der Liste auf. Refresh notwendig = bad UX.

Daten neu laden sollte mit `invalidateAll()` funktionieren.

2024-07-15 11:16 UTC, felixguendling commented on src/routes/taxi/+page.svelte
> +	let newVehicle = $state<Promise<Response>>();
Konsistenz: Englische Variablen Namen

2024-07-15 11:16 UTC, felixguendling commented on src/routes/taxi/+page.svelte
> +					<div>
Design: Abstand nach oben

2024-07-15 13:20 UTC, CmdrTMir commented on src/routes/taxi/+page.svelte
> +					<div>
Ist damit gemeint, dass die Einrückung nicht gut ist? Ich bin mir nicht sicher, an welcher Stelle das ist. Ich habe Änderungen gemacht und nochmal run format ausgeführt, ich hoffe das hat es behoben.

2024-07-15 15:06 UTC, steffenheger approved these changes

2024-07-16 08:29 UTC, felixguendling commented
- Regex gefixt: muss von Anfang bis Ende gehen
- Duplikate geprüft (unique constraint auf DB row)

2024-07-16 08:29 UTC, merged